<?php
/*
| For additional options see
| https://github.com/octobercms/october/blob/master/config/cms.php
*/

return [
    'activeTheme' => env('CMS_ACTIVE_THEME', 'demo'),
    'edgeUpdates' => env('CMS_EDGE_UPDATES', false),
    'disableCoreUpdates' => env('CMS_DISABLE_CORE_UPDATES', true),
    'backendTimezone' => env('TZ', 'UTC'),
    'backendSkin' => env('CMS_BACKEND_SKIN', 'Backend\Skins\Standard'),
    'linkPolicy' => env('CMS_LINK_POLICY', 'detect'),
    'backendForceSecure' => env('CMS_BACKEND_FORCE_SECURE', false),
    'backendUri' => env('OCTOBER_CMS_BACKEND_URI') ?: 'backend',
    'defaultMask' => [
        'file' => env('CMS_DEFAULT_MASK_FILE', '664'),
        'folder' =>  env('CMS_DEFAULT_MASK_FOLDER', '775'),
    ],
    
    /*
    |--------------------------------------------------------------------------
    | Resource storage
    |--------------------------------------------------------------------------
    |
    | Specifies the configuration for resource storage, such as media and
    | upload files. These resources are used:
    |
    | media   - generated by the media manager.
    | uploads - generated by attachment model relationships.
    |
    | For each resource you can specify:
    |
    | disk   - filesystem disk, as specified in filesystems.php config.
    | folder - a folder prefix for storing all generated files inside.
    | path   - the public path relative to the application base URL,
    |          or you can specify a full URL path.
    */

    'storage' => [

        'uploads' => [
            'disk'   => env('FS_DEFAULT', 'local'),
            'folder' => 'uploads',
            'path'   => env('FS_PATH_UPLOAD', '/storage/app/uploads'),
        ],

        'media' => [
            'disk'   => env('FS_DEFAULT', 'local'),
            'folder' => 'media',
            'path'   => env('FS_PATH_MEDIA', '/storage/app/media'),
        ],

    ],
    
];
